### ISSUE TITLE
게시판 글 한번에 여러개 삭제하기

### ISSUE THREAD

**Issue by sjHong645** [sponbob-pat/board#1]
1) 조회 화면에 `checkbox`를 추가하자.

2) 하나 이상 선택하면 `삭제`될 수 있게 하자

**Comment by sjHong645** [comment]
[해당 커밋](https://github.com/sponbob-pat/board/commit/5b06433a6e90b9f83963c5e058d0cfec5e667a9b) 

간략히 정리하면
1) index.mustache에서 선택한 checkbox들을 `List 자료형`으로 보낸다.
2) 해당 id값들을 `delete`하고 `원래화면 (index.mustache)`에 돌아간다.

[관련 내용 정리](https://sponbob-pat.tistory.com/18)

**Comment by sponbob-pat** [comment]
이에 대한 테스트 코드를 작성하자
